# Generated by Django 5.2.10 on 2026-02-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_rename_work_to_podramnik_and_add_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baguette',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ширина (м)'),
        ),
    ]
