# Generated by Django 5.2.10 on 2026-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0003_alter_baguette_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passepartout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Длина (м)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ширина (м)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Паспарту',
                'verbose_name_plural': 'Паспарту',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='podramnik',
            name='consumption',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Расход (м)'),
        ),
    ]
