# Generated by Django 5.2.10 on 2026-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0004_passepartout_podramnik_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passepartout',
            name='length',
        ),
        migrations.RemoveField(
            model_name='passepartout',
            name='width',
        ),
        migrations.AddField(
            model_name='passepartout',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (руб)'),
        ),
    ]
