# Generated by Django 5.2.10 on 2026-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_remove_passepartout_length_remove_passepartout_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baguette',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Штрихкод'),
        ),
    ]
