# Generated by Django 5.2.10 on 2026-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0008_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_size_x1', models.DecimalField(decimal_places=2, default=60, help_text='Максимальный размер первой стороны для малых рам', max_digits=6, verbose_name='Максимальный размер первой стороны (см)')),
                ('max_size_x2', models.DecimalField(decimal_places=2, default=50, help_text='Максимальный размер второй стороны для малых рам', max_digits=6, verbose_name='Максимальный размер второй стороны (см)')),
                ('multiplier_for_large', models.DecimalField(decimal_places=2, default=1.5, help_text='Коэффициент умножения стоимости работ для рам больше порогового размера', max_digits=4, verbose_name='Коэффициент для больших рам')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки стоимости работ',
                'verbose_name_plural': 'Настройки стоимости работ',
            },
        ),
    ]
