# Generated by Django 5.2.10 on 2026-02-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0009_workpricesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='frame_type',
            field=models.CharField(choices=[('any', 'Любой тип рамы'), ('simple', 'Простая рама (без паспарту)'), ('with_passepartout', 'Рама с паспарту')], default='any', help_text='Тип рам, для которых применима эта работа', max_length=50, verbose_name='Тип рамы'),
        ),
    ]
