# Generated by Django 5.2.10 on 2026-02-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0010_work_frame_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='baguette',
            field=models.ForeignKey(blank=True, help_text='Работа применяется при выборе этого багета', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frames.baguette', verbose_name='Багет'),
        ),
        migrations.AddField(
            model_name='work',
            name='glass',
            field=models.ForeignKey(blank=True, help_text='Работа применяется при выборе этого стекла', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frames.glass', verbose_name='Стекло'),
        ),
        migrations.AddField(
            model_name='work',
            name='passepartout',
            field=models.ForeignKey(blank=True, help_text='Работа применяется при выборе этого паспарту', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frames.passepartout', verbose_name='Паспарту'),
        ),
        migrations.AddField(
            model_name='work',
            name='podramnik',
            field=models.ForeignKey(blank=True, help_text='Работа применяется при выборе этого подрамника', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frames.podramnik', verbose_name='Подрамник'),
        ),
        migrations.AddField(
            model_name='work',
            name='stretch',
            field=models.ForeignKey(blank=True, help_text='Работа применяется при выборе этой натяжки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frames.stretch', verbose_name='Натяжка'),
        ),
    ]
