# Generated by Django 5.2.10 on 2026-02-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0011_work_baguette_work_glass_work_passepartout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='frame_type',
        ),
    ]
