# Generated by Django 5.2.10 on 2026-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0012_remove_work_frame_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='baguette',
        ),
        migrations.RemoveField(
            model_name='work',
            name='glass',
        ),
        migrations.RemoveField(
            model_name='work',
            name='passepartout',
        ),
        migrations.RemoveField(
            model_name='work',
            name='podramnik',
        ),
        migrations.RemoveField(
            model_name='work',
            name='stretch',
        ),
        migrations.AddField(
            model_name='work',
            name='material_type',
            field=models.CharField(blank=True, choices=[('', 'Не привязана к материалу'), ('baguette', 'Багет'), ('podramnik', 'Подрамник'), ('glass', 'Стекло'), ('passepartout', 'Паспарту'), ('stretch', 'Натяжка'), ('backing', 'Подкладка'), ('hardware', 'Фурнитура'), ('molding', 'Молдинг'), ('trosik', 'Тросик'), ('podveski', 'Подвески')], default='', help_text='Тип материала, при выборе которого автоматически добавляется эта работа', max_length=50, verbose_name='Тип материала'),
        ),
    ]
