# Generated by Django 5.2.10 on 2026-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0013_remove_work_baguette_remove_work_glass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passepartout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='passepartout/', verbose_name='Фото'),
        ),
    ]
