# Generated by Django 5.2.10 on 2026-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0014_passepartout_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='backing',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в штуках. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (шт)'),
        ),
        migrations.AddField(
            model_name='baguette',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в метрах. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (м)'),
        ),
        migrations.AddField(
            model_name='glass',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в кв.м. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (кв.м)'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в штуках. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (шт)'),
        ),
        migrations.AddField(
            model_name='material',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в штуках. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (шт)'),
        ),
        migrations.AddField(
            model_name='molding',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в метрах. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (м)'),
        ),
        migrations.AddField(
            model_name='package',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в штуках. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (шт)'),
        ),
        migrations.AddField(
            model_name='passepartout',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в штуках (листах). Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (шт)'),
        ),
        migrations.AddField(
            model_name='podramnik',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в штуках. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (шт)'),
        ),
        migrations.AddField(
            model_name='podveski',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в штуках. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (шт)'),
        ),
        migrations.AddField(
            model_name='stretch',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в кв.м. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (кв.м)'),
        ),
        migrations.AddField(
            model_name='trosik',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в метрах. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (м)'),
        ),
    ]
