# Generated by Django 5.2.10 on 2026-08-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0015_add_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foamboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за кв.м (руб)')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Фактическое наличие на складе в кв.м. Списывается при каждом заказе.', max_digits=12, verbose_name='Количество на складе (кв.м)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пенокартон',
                'verbose_name_plural': 'Пенокартон (накатка)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Код 1С')),
                ('operation_type', models.CharField(choices=[('rama', 'Изготовление рамы'), ('rama2', 'Изготовление двойных рам'), ('rama3', 'Изготовление тройных рам'), ('passepartout', 'Паспарту'), ('passepartout2', 'Паспарту второе'), ('passepartout3', 'Паспарту третье'), ('backing', 'Резка подкладки'), ('backing2', 'Резка подкладки2'), ('glass', 'Резка стекла'), ('glass2', 'Резка стекла2'), ('podramnik', 'Подрамник'), ('foamboard', 'Накатка на пенокартон'), ('stretch', 'Натяжка холста'), ('molding', 'Молдинг'), ('complexity_frame', 'Сложность рамы'), ('complexity_pp', 'Сложность паспарту'), ('complexity_mount', 'Крепление объекта'), ('package', 'Упаковка')], db_index=True, max_length=32, verbose_name='Вид операции')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('size_from', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='От (см)')),
                ('size_to', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='До (см)')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Технологическая операция (работа)',
                'verbose_name_plural': 'Технологические операции (работы)',
                'ordering': ['operation_type', 'size_from'],
            },
        ),
    ]
