# Generated by Django 5.2.10 on 2026-08-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0017_seed_tech_operations'),
        ('orders', '0010_remove_order_work_alter_order_backing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='WorkPriceSettings',
        ),
    ]
