# Generated by Django 5.2.10 on 2026-01-30 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Размер X1 (см)')),
                ('x2', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Размер X2 (см)')),
                ('hardware_quantity', models.PositiveIntegerField(default=1, verbose_name='Количество фурнитуры')),
                ('molding_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расход молдинга (м)')),
                ('trosik_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина тросика (м)')),
                ('podveski_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество подвесок')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговая цена (руб)')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('ready', 'Готов'), ('issued', 'Выдан')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('backing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.backing', verbose_name='Подкладка')),
                ('baguette', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.baguette', verbose_name='Багет')),
                ('glass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.glass', verbose_name='Стекло')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.hardware', verbose_name='Фурнитура')),
                ('molding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.molding', verbose_name='Молдинг')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.package', verbose_name='Упаковка')),
                ('podveski', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.podveski', verbose_name='Подвески')),
                ('trosik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.trosik', verbose_name='Тросик')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
