# Generated by Django 5.2.10 on 2026-01-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0002_rename_work_to_podramnik_and_add_material'),
        ('orders', '0002_rename_work_to_podramnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='hardware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.hardware', verbose_name='Фурнитура'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hardware_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество фурнитуры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.package', verbose_name='Упаковка'),
        ),
    ]
