# Generated by Django 5.2.10 on 2026-02-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_remove_passepartout_length_remove_passepartout_width_and_more'),
        ('orders', '0003_make_hardware_and_package_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='passepartout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.passepartout', verbose_name='Паспарту'),
        ),
        migrations.AddField(
            model_name='order',
            name='passepartout_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Длина паспарту (см)'),
        ),
        migrations.AddField(
            model_name='order',
            name='passepartout_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ширина паспарту (см)'),
        ),
    ]
