# Generated by Django 5.2.10 on 2026-02-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_frames_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Аванс (руб)'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Долг (руб)'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата исполнения заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='наличные', max_length=50, null=True, verbose_name='Способ оплаты'),
        ),
    ]
