# Generated by Django 5.2.10 on 2026-02-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0007_stretch'),
        ('orders', '0006_order_advance_payment_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='podramnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.podramnik', verbose_name='Подрамник'),
        ),
    ]
