# Generated by Django 5.2.10 on 2026-02-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0008_work'),
        ('orders', '0007_alter_order_podramnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.work', verbose_name='Работа'),
        ),
    ]
