# Generated by Django 5.2.10 on 2026-08-06 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0017_seed_tech_operations'),
        ('orders', '0009_add_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='work',
        ),
        migrations.AlterField(
            model_name='order',
            name='backing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.backing', verbose_name='Подкладка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='glass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.glass', verbose_name='Стекло'),
        ),
    ]
