# Generated by Django 5.2.10 on 2026-08-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0018_delete_work_delete_workpricesettings'),
        ('orders', '0010_remove_order_work_alter_order_backing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='baguette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.baguette', verbose_name='Багет'),
        ),
    ]
