# Generated by Django 5.2.10 on 2026-08-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_baguette'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_complexity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Дополнительная сумма за сложность, вводится вручную. Добавляется к цене полностью.', max_digits=12, verbose_name='Сложность (вручную, руб)'),
        ),
    ]
