# Generated by Django 5.2.10 on 2026-08-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0018_delete_work_delete_workpricesettings'),
        ('orders', '0012_order_manual_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stretch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='frames.stretch', verbose_name='Натяжка'),
        ),
    ]
