# Generated by Django 5.2.10 on 2026-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_stretch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество пакетов'),
        ),
    ]
